name: Continuous Integration

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      run: terraform fmt -recursive -check -no-color

    - name: Terraform validate
      env:
        TF_VAR_branch: ${{ vars.BRANCH }}
        TF_VAR_kms_arn: ${{ secrets.KMS_KEY}}
        TF_VAR_domain: ${{ secrets.DOMAIN}}
      run: |
        cd infrastructure
        terraform init -backend=false -no-color
        terraform validate -no-color
  unitpytest:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Run tests
      run: |
        pipenv run unit_test
  unitqUnit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]  # Specify Node.js versions here
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run QUnit tests
      run: npm test
