name: Continuous Integration

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      run: terraform fmt -recursive -check -no-color

    - name: Terraform validate
      env:
        TF_VAR_branch: ${{ vars.BRANCH }}
        TF_VAR_kms_arn: ${{ secrets.KMS_KEY}}
        TF_VAR_domain: ${{ secrets.DOMAIN}}
      run: |
        cd infrastructure
        terraform init -backend=false -no-color
        terraform validate -no-color

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Run tests
      run: |
        pipenv run unit_test
