name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      env:
        BUCKET: ${{ secrets.BUCKET }}
        BRANCH: ${{ vars.GITHUB_HEAD_REF }}
      run: terraform init -backend-config="bucket=${BUCKET}" -backend-config="key=${BRANCH}.tfstate"

    - name: Terraform Apply
      run: terraform apply -auto-approve
