name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
        BRANCH: ${{ vars.BRANCH }}
      run: |
        cd infrastructure
        terraform init -backend-config="bucket=${BUCKET}" -backend-config="key=${BRANCH}.tfstate"

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_branch_name: ${{ vars.BRANCH }}
        TF_VAR_kms_arn: ${{ secrets.KMS_KEY}}
      run: |
        cd infrastructure
        terraform apply -auto-approve
